name: Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Server
        run: |
          curl -s "${{ secrets.RENDER_URL }}/keep-alive"
        continue-on-error: true